name: run

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 10 * * *"  # daily at 10:15 UTC; adjust as needed

concurrency:
  group: daily-discord-batch
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}
      DISCORD_IDS_CHANNEL_ID: ${{ secrets.DISCORD_IDS_CHANNEL_ID }}
      DISCORD_STATE_CHANNEL_ID: ${{ secrets.DISCORD_STATE_CHANNEL_ID }}
      WOS_SECRET: ${{ secrets.WOS_SECRET }}
      DEBUG: "0"
      REDEEM_PACING_SECONDS: "1.6"
      REQUEST_TIMEOUT_SECONDS: "20"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (tesseract OCR)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends tesseract-ocr

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow pytesseract

      - name: Preflight env echo (redacted)
        run: |
          echo "Codes channel set:  $([ -n "$DISCORD_CODES_CHANNEL_ID" ] && echo true || echo false)"
          echo "IDs channel set:    $([ -n "$DISCORD_IDS_CHANNEL_ID" ] && echo true || echo false)"
          echo "State channel set:  $([ -n "$DISCORD_STATE_CHANNEL_ID" ] && echo true || echo false)"
          echo "WOS secret set:     $([ -n "$WOS_SECRET" ] && echo true || echo false)"

      - name: Run daily job
        run: |
          set -e
          python scripts/daily_discord_batch_v2.py
