name: WOS Discord Daily

on:
  schedule:
    - cron: "15 11 * * *"   # adjust time
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}
      DISCORD_IDS_CHANNEL_ID: ${{ secrets.DISCORD_IDS_CHANNEL_ID }}
      DISCORD_STATE_CHANNEL_ID: ${{ secrets.DISCORD_STATE_CHANNEL_ID }}
      WOS_SECRET: ${{ secrets.WOS_SECRET }}
      REDEEM_PACING_SECONDS: "1.8"
      DEBUG: "1"                        # turn off later if too chatty
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (Tesseract)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow pytesseract easyocr playwright

      - name: Install Playwright Chromium
        run: |
          python -m playwright install --with-deps chromium

      - name: Run daily job
        run: |
          python scripts/daily_discord_batch.py
