name: WOS Gift Codes Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '25 16 * * *'   # adjust (UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (requests + Playwright + Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          python -m playwright install --with-deps chromium

      - name: Preflight env echo (redacted)
        run: |
          echo "Codes channel set:  $([ -n "$DISCORD_CODES_CHANNEL_ID" ] && echo true || echo false)"
          echo "IDs channel set:    $([ -n "$DISCORD_IDS_CHANNEL_ID" ] && echo true || echo false)"
          echo "State channel set:  $([ -n "$DISCORD_STATE_CHANNEL_ID" ] && echo true || echo false)"
          echo "WOS secret set:     $([ -n "$WOS_SECRET" ] && echo true || echo false)"

      - name: Run daily job
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}
          DISCORD_IDS_CHANNEL_ID: ${{ secrets.DISCORD_IDS_CHANNEL_ID }}
          DISCORD_STATE_CHANNEL_ID: ${{ secrets.DISCORD_STATE_CHANNEL_ID }}
          WOS_SECRET: ${{ secrets.WOS_SECRET }}
          DEBUG: "0"
          REDEEM_PACING_SECONDS: "1.25"
        run: |
          set -e
          python scripts/daily_discord_batch_v2.py
