name: WOS Gift Codes Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '25 16 * * *'  # adjust as desired (UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (tesseract OCR)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow pytesseract

      - name: Sanity check (show script header; ensure no playwright)
        run: |
          echo "HEAD: $(git rev-parse --short HEAD)"
          sed -n '1,30p' scripts/daily_discord_batch_v2.py
          (grep -Rin "playwright" scripts || true)

      - name: Run daily job
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}
          DISCORD_IDS_CHANNEL_ID: ${{ secrets.DISCORD_IDS_CHANNEL_ID }}
          DISCORD_STATE_CHANNEL_ID: ${{ secrets.DISCORD_STATE_CHANNEL_ID }}
          WOS_SECRET: ${{ secrets.WOS_SECRET }}
          DEBUG: "0"
        run: |
          set -e
          python scripts/daily_discord_batch_v2.py
