name: WOS Gift Bot (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "23 11 * * *"  # adjust to your preferred time (UTC)

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (Tesseract + Playwright deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
          python -m pip install --upgrade pip

      - name: Install Python libs
        run: |
          pip install requests pillow pytesseract playwright
          python -m playwright install --with-deps chromium

      - name: Preflight env echo (redacted)
        run: |
          echo "Codes channel set:  $([ -n "$DISCORD_CODES_CHANNEL_ID" ] && echo true || echo false)"
          echo "IDs channel set:    $([ -n "$DISCORD_IDS_CHANNEL_ID" ] && echo true || echo false)"
          echo "State channel set:  $([ -n "$DISCORD_STATE_CHANNEL_ID" ] && echo true || echo false)"
          echo "WOS secret set:     $([ -n "$WOS_SECRET" ] && echo true || echo false)"

      - name: Locate script
        run: |
          set -e
          test -f scripts/daily_discord_batch.py
          echo "Found script: scripts/daily_discord_batch.py"

      - name: Run daily job
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}
          DISCORD_IDS_CHANNEL_ID: ${{ secrets.DISCORD_IDS_CHANNEL_ID }}
          DISCORD_STATE_CHANNEL_ID: ${{ secrets.DISCORD_STATE_CHANNEL_ID }}
          WOS_SECRET: ${{ secrets.WOS_SECRET }}
          REDEEM_PACING_SECONDS: "1.4"
          DEBUG: "0"
        run: |
          set -e
          python scripts/daily_discord_batch.py
