name: discord_daily_batch

on:
  workflow_dispatch:
  schedule:
    - cron: '17 9 * * *'  # once daily; adjust as needed

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}
      DISCORD_IDS_CHANNEL_ID: ${{ secrets.DISCORD_IDS_CHANNEL_ID }}
      DISCORD_STATE_CHANNEL_ID: ${{ secrets.DISCORD_STATE_CHANNEL_ID }}
      WOS_SECRET: ${{ secrets.WOS_SECRET }}
      DEBUG: "0"
      REDEEM_PACING_SECONDS: "1.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install deps (requests + playwright + easyocr)
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow
          pip install playwright==1.45.0
          pip install easyocr==1.7.1
          # Install Playwright browsers
          python -m playwright install --with-deps chromium

      - name: Preflight env echo (redacted)
        run: |
          echo "Codes channel set:  $([ -n "$DISCORD_CODES_CHANNEL_ID" ] && echo true || echo false)"
          echo "IDs channel set:    $([ -n "$DISCORD_IDS_CHANNEL_ID" ] && echo true || echo false)"
          echo "State channel set:  $([ -n "$DISCORD_STATE_CHANNEL_ID" ] && echo true || echo false)"
          echo "WOS secret set:     $([ -n "$WOS_SECRET" ] && echo true || echo false)"

      - name: Run daily job
        run: |
          set -e
          python scripts/daily_discord_batch_v3.py
