name: Discord-driven daily batch

on:
  schedule:
    - cron: "0 08 * * *"   # runs daily at 08:00 UTC; change as needed
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    concurrency:
      group: discord-daily-batch
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (requests + playwright + Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          python -m playwright install --with-deps chromium

      - name: Run daily job (read Discord → update roster → redeem → furnace diffs → post summary)
        env:
          DISCORD_BOT_TOKEN:         ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CODES_CHANNEL_ID:  ${{ secrets.DISCORD_CODES_CHANNEL_ID }}   # #gift_code_axe
          DISCORD_IDS_CHANNEL_ID:    ${{ secrets.DISCORD_IDS_CHANNEL_ID }}     # #3349_axe
          DISCORD_STATE_CHANNEL_ID:  ${{ secrets.DISCORD_STATE_CHANNEL_ID }}   # #wosbot_state (used for state file + summary)
          WOS_SECRET:                ${{ secrets.WOS_SECRET }}
          DAILY_RUN_UTC:             ${{ vars.DAILY_RUN_UTC }}                 # optional; e.g., "08:00"
        run: |
          python scripts/daily_discord_batch.py
