name: WOS Gift Redeemer (Daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-redeemer:
    runs-on: ubuntu-22.04  # avoid 24.04 surprises
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          python -m playwright install --with-deps chromium

      - name: Run gift redeemer
        env:
          WOS_SECRET: ${{ secrets.WOS_SECRET }}
          GIFT_CODE:  ${{ secrets.GIFT_CODE }}
          FIDS:       ${{ secrets.FIDS }}
        run: python scripts/run_wos_redeem.py
