# .github/workflows/discord_daily_batch.yml
name: Discord-driven daily batch

on:
  schedule:
    - cron: "0 08 * * *"   # change time as needed (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: discord-daily-batch
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Run daily job
        env:
          DISCORD_BOT_TOKEN:        ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CODES_CHANNEL_ID: ${{ secrets.DISCORD_CODES_CHANNEL_ID }}   # ← gift_code_axe
          DISCORD_IDS_CHANNEL_ID:   ${{ secrets.DISCORD_IDS_CHANNEL_ID }}     # ← 3349_axe
          DISCORD_SUMMARY_CHANNEL_ID: ${{ secrets.DISCORD_SUMMARY_CHANNEL_ID }} # optional; falls back to codes channel
          WOS_SECRET:               ${{ secrets.WOS_SECRET }}
        run: |
          python scripts/daily_discord_batch.py

      - name: Persist checkpoint and roster
        if: always()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/wos_state.json .github/roster.json || true
          git commit -m "update daily state" || echo "no changes"
          git push || echo "no push"
